---
baseURL: https://example.com
languageCode: en-us
title: M.K Blog
pygmentsstyle: monokai
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
